### ISSUE TITLE
Bot Uids

### ISSUE THREAD

**Issue by UnknownSilicon** [RMHSProgrammingClub/Bot-Client#3]
The `bot.getUid()` method does not work. It always returns -1

**Comment by n9Mtq4** [comment]
The bot uid will always return -1 if the server doesn't have support for it. The server with support for bot uids has not been released as a jar yet, but you can download and run the ruby code if you want.

**Comment by n9Mtq4** [comment]
``` kotlin
val uid = ((json["uid"] ?: -1L) as Long).toInt() // bot id is -1 if server doesn't have support
```

https://github.com/RMHSProgrammingClub/Bot-Client/blob/master/kotlin/src/main/kotlin/com/n9mtq4/botclient/ControllableBot.kt#L284
