### ISSUE TITLE
Vision

### ISSUE THREAD

**Issue by UnknownSilicon** [RMHSProgrammingClub/Bot-Client#4]
Vision does not seem to work either. 
`for (WorldObject object : bot.getVision()) {
                        if (object.isWall() && object.getY() == bot.getY() + 1) {
                            System.out.println("wall");
                        }
 }`

**Comment by n9Mtq4** [comment]
This is a known server issue that is currently being worked on.
https://github.com/RMHSProgrammingClub/Bot-Server/issues/4
